//! GTK 4 + libadwaita rewrite of Rclone Manager.

pub mod action_order;
pub mod alerts;
pub mod ansi;
pub mod automation;
pub mod backend_options;
pub mod backup;
pub mod checks;
pub mod command_options;
pub mod connection;
pub mod cron;
pub mod dnd;
pub mod fileops;
pub mod flags;
pub mod i18n;
pub mod interactive;
pub mod jobs;
pub mod keyring;
pub mod layout;
pub mod logs;
pub mod markdown;
pub mod media;
pub mod migrate;
pub mod mime;
pub mod mount_plugin;
pub mod mqtt;
pub mod navigation;
pub mod operations;
pub mod path_inspection;
pub mod path_kind;
pub mod picker;
pub mod platform;
pub mod presets;
pub mod providers;
pub mod rclone;
pub mod refresh;
pub mod rename;
pub mod repair;
pub mod restrict;
pub mod security;
pub mod settings;
pub mod smtp;
pub mod store;
pub mod syntax;
pub mod textfix;
pub mod transfers;
pub mod tray_menu;
pub mod updater;
pub mod user_templates;
pub mod validators;
pub mod value_mapper;
pub mod vfs;
pub mod watch;

pub const APP_ID: &str = "io.github.zarestia_dev.rclone-manager";
pub const APP_NAME: &str = "Rclone Manager";
pub const APP_VERSION: &str = env!("CARGO_PKG_VERSION");
