// Rclone Remote Control (RC) API endpoints
//
// This module provides organized access to all rclone RC API endpoints.
// The endpoints are categorized for easier management and discovery.
//
// Generated by update-endpoints.cjs from live rclone rc/list.
// Total: 104 endpoints across 14 modules.
//
// To regenerate:
//   npm run sync:endpoints
//   npm run sync:endpoints -- --live
//   npm run sync:endpoints -- --live --url http://127.0.0.1:5572
/// Core system endpoints
pub mod core {

    /// Set the bandwidth limit.
    ///
    /// This sets the bandwidth limit to the string passed in. This should be
    /// a single bandwidth limit entry or a pair of upload:download bandwidth.
    ///
    /// Eg
    ///
    /// ```text
    /// rclone rc core/bwlimit rate=off
    /// {
    /// "bytesPerSecond": -1,
    /// "bytesPerSecondTx": -1,
    /// "bytesPerSecondRx": -1,
    /// "rate": "off"
    /// }
    /// rclone rc core/bwlimit rate=1M
    /// {
    /// "bytesPerSecond": 1048576,
    /// "bytesPerSecondTx": 1048576,
    /// "bytesPerSecondRx": 1048576,
    /// "rate": "1M"
    /// }
    /// rclone rc core/bwlimit rate=1M:100k
    /// {
    /// "bytesPerSecond": 1048576,
    /// "bytesPerSecondTx": 1048576,
    /// "bytesPerSecondRx": 131072,
    /// "rate": "1M"
    /// }
    ///
    ///
    /// ```
    /// If the rate parameter is not supplied then the bandwidth is queried
    ///
    /// ```text
    /// rclone rc core/bwlimit
    /// {
    /// "bytesPerSecond": 1048576,
    /// "bytesPerSecondTx": 1048576,
    /// "bytesPerSecondRx": 1048576,
    /// "rate": "1M"
    /// }
    ///
    /// ```
    /// The format of the parameter is exactly the same as passed to --bwlimit
    /// except only one bandwidth may be specified.
    ///
    /// In either case "rate" is returned as a human-readable string, and
    /// "bytesPerSecond" is returned as a number.
    pub const BWLIMIT: &str = "core/bwlimit";

    /// Run a rclone terminal command over rc.
    ///
    /// This takes the following parameters:
    ///
    /// - command - a string with the command name.
    /// - arg - a list of arguments for the backend command.
    /// - opt - a map of string to string of options.
    /// - returnType - one of ("COMBINED_OUTPUT", "STREAM", "STREAM_ONLY_STDOUT", "STREAM_ONLY_STDERR").
    ///     - Defaults to "COMBINED_OUTPUT" if not set.
    ///     - The STREAM returnTypes will write the output to the body of the HTTP message.
    ///     - The COMBINED_OUTPUT will write the output to the "result" parameter.
    ///
    /// Returns:
    ///
    /// - result - result from the backend command.
    ///     - Only set when using returnType "COMBINED_OUTPUT".
    /// - error     - set if rclone exits with an error code.
    /// - returnType - one of ("COMBINED_OUTPUT", "STREAM", "STREAM_ONLY_STDOUT", "STREAM_ONLY_STDERR").
    ///
    /// Example:
    ///
    /// ```text
    /// rclone rc core/command command=ls -a mydrive:/ -o max-depth=1
    /// rclone rc core/command -a ls -a mydrive:/ -o max-depth=1
    ///
    /// ```
    /// Returns:
    ///
    /// ```text
    /// {
    ///     "error": false,
    ///     "result": "<Raw command line output>"
    /// }
    ///
    /// OR
    /// {
    ///     "error": true,
    ///     "result": "<Raw command line output>"
    /// }
    ///
    /// ```
    pub const COMMAND: &str = "core/command";

    /// List the local disks
    ///
    /// This does not take any parameters
    ///
    /// This call is for rclone GUI programs to enumerate local disks and
    /// important directories for doing transfers to and from. The list
    /// returned will include the root directory and the user's home directory
    /// and any mounted disks. The returned items should be usable directly as
    /// remotes.
    ///
    /// Returns:
    ///
    /// - disks
    ///     - This is an array of strings of local disk names
    pub const DISKS: &str = "core/disks";

    /// Returns disk usage of a locally attached disk.
    ///
    /// This returns the disk usage for the local directory passed in as dir.
    ///
    /// If the directory is not passed in, it defaults to the directory
    /// pointed to by --cache-dir.
    ///
    /// - dir - string (optional)
    ///
    /// Returns:
    ///
    /// ```text
    /// {
    ///     "dir": "/",
    ///     "info": {
    ///         "Available": 361769115648,
    ///         "Free": 361785892864,
    ///         "Total": 982141468672
    ///     }
    /// }
    /// ```
    pub const DU: &str = "core/du";

    /// Runs a garbage collection.
    ///
    /// This tells the go runtime to do a garbage collection run.  It isn't
    /// necessary to call this normally, but it can be useful for debugging
    /// memory problems.
    pub const GC: &str = "core/gc";

    /// Returns list of stats.
    ///
    /// This returns list of stats groups currently in memory.
    ///
    /// Returns the following values:
    /// ```text
    /// {
    ///     "groups":  an array of group names:
    ///         [
    ///             "group1",
    ///             "group2",
    ///             ...
    ///         ]
    /// }
    /// ```
    pub const GROUP_LIST: &str = "core/group-list";

    /// Returns the memory statistics
    ///
    /// This returns the memory statistics of the running program.  What the values mean
    /// are explained in the go docs: https://golang.org/pkg/runtime/#MemStats
    ///
    /// The most interesting values for most people are:
    ///
    /// - HeapAlloc - this is the amount of memory rclone is actually using
    /// - HeapSys - this is the amount of memory rclone has obtained from the OS
    /// - Sys - this is the total amount of memory requested from the OS
    ///    - It is virtual memory so may include unused memory
    pub const MEMSTATS: &str = "core/memstats";

    /// Obscures a string passed in.
    ///
    /// Pass a clear string and rclone will obscure it for the config file:
    /// - clear - string
    ///
    /// Returns:
    /// - obscured - string
    pub const OBSCURE: &str = "core/obscure";

    /// Return PID of current process
    ///
    /// This returns PID of current process.
    /// Useful for stopping rclone process.
    pub const PID: &str = "core/pid";

    /// Terminates the app.
    ///
    /// (Optional) Pass an exit code to be used for terminating the app:
    /// - exitCode - int
    pub const QUIT: &str = "core/quit";

    /// Returns stats about current transfers.
    ///
    /// This returns all available stats:
    ///
    /// ```text
    /// rclone rc core/stats
    ///
    /// ```
    /// If group is not provided then summed up stats for all groups will be
    /// returned.
    ///
    /// Parameters
    ///
    /// - group - name of the stats group (string, optional)
    /// - short - if true will not return the transferring and checking arrays (boolean, optional)
    ///
    /// Returns the following values:
    ///
    /// ```text
    /// {
    ///     "bytes": total transferred bytes since the start of the group,
    ///     "checks": number of files checked,
    ///     "deletedDirs": number of directories deleted,
    ///     "deletes" : number of files deleted,
    ///     "elapsedTime": time in floating point seconds since rclone was started,
    ///     "errors": number of errors,
    ///     "eta": estimated time in seconds until the group completes,
    ///     "fatalError": boolean whether there has been at least one fatal error,
    ///     "lastError": last error string,
    ///     "renames" : number of files renamed,
    ///     "listed" : number of directory entries listed,
    ///     "retryError": boolean showing whether there has been at least one non-NoRetryError,
    ///         "serverSideCopies": number of server side copies done,
    ///         "serverSideCopyBytes": number bytes server side copied,
    ///         "serverSideMoves": number of server side moves done,
    ///         "serverSideMoveBytes": number bytes server side moved,
    ///     "speed": average speed in bytes per second since start of the group,
    ///     "totalBytes": total number of bytes in the group,
    ///     "totalChecks": total number of checks in the group,
    ///     "totalTransfers": total number of transfers in the group,
    ///     "transferTime" : total time spent on running jobs,
    ///     "transfers": number of transferred files,
    ///     "transferring": an array of currently active file transfers:
    ///         [
    ///             {
    ///                 "bytes": total transferred bytes for this file,
    ///                 "eta": estimated time in seconds until file transfer completion
    ///                 "name": name of the file,
    ///                 "percentage": progress of the file transfer in percent,
    ///                 "speed": average speed over the whole transfer in bytes per second,
    ///                 "speedAvg": current speed in bytes per second as an exponentially weighted moving average,
    ///                 "size": size of the file in bytes
    ///             }
    ///         ],
    ///     "checking": an array of names of currently active file checks
    ///         []
    /// }
    /// ```
    /// Values for "transferring", "checking" and "lastError" are only assigned if data is available.
    /// The value for "eta" is null if an eta cannot be determined.
    pub const STATS: &str = "core/stats";

    /// Delete stats group.
    ///
    /// This deletes entire stats group.
    ///
    /// Parameters
    ///
    /// - group - name of the stats group (string)
    pub const STATS_DELETE: &str = "core/stats-delete";

    /// Reset stats.
    ///
    /// This clears counters, errors and finished transfers for all stats or specific
    /// stats group if group is provided.
    ///
    /// Parameters
    ///
    /// - group - name of the stats group (string)
    pub const STATS_RESET: &str = "core/stats-reset";

    /// Returns stats about completed transfers.
    ///
    /// This returns stats about completed transfers:
    ///
    /// ```text
    /// rclone rc core/transferred
    ///
    /// ```
    /// If group is not provided then completed transfers for all groups will be
    /// returned.
    ///
    /// Note only the last 100 completed transfers are returned.
    ///
    /// Parameters
    ///
    /// - group - name of the stats group (string)
    ///
    /// Returns the following values:
    /// ```text
    /// {
    ///     "transferred":  an array of completed transfers (including failed ones):
    ///         [
    ///             {
    ///                 "name": name of the file,
    ///                 "size": size of the file in bytes,
    ///                 "bytes": total transferred bytes for this file,
    ///                 "checked": if the transfer is only checked (skipped, deleted),
    ///                 "what": the purpose of the transfer (transferring, deleting, checking, importing, hashing, merging, listing, moving, renaming),
    ///                 "timestamp": integer representing millisecond unix epoch,
    ///                 "error": string description of the error (empty if successful),
    ///                 "jobid": id of the job that this transfer belongs to
    ///             }
    ///         ]
    /// }
    /// ```
    pub const TRANSFERRED: &str = "core/transferred";

    /// Shows the current version of rclone, Go and the OS.
    ///
    /// This shows the current versions of rclone, Go and the OS:
    ///
    /// - version - rclone version, e.g. "v1.71.2"
    /// - decomposed - version number as [major, minor, patch]
    /// - isGit - boolean - true if this was compiled from the git version
    /// - isBeta - boolean - true if this is a beta version
    /// - os - OS in use as according to Go GOOS (e.g. "linux")
    /// - osKernel - OS Kernel version (e.g. "6.8.0-86-generic (x86_64)")
    /// - osVersion -  OS Version (e.g. "ubuntu 24.04 (64 bit)")
    /// - osArch - cpu architecture in use (e.g. "arm64 (ARMv8 compatible)")
    /// - arch - cpu architecture in use according to Go GOARCH (e.g. "arm64")
    /// - goVersion - version of Go runtime in use (e.g. "go1.25.0")
    /// - linking - type of rclone executable (static or dynamic)
    /// - goTags - space separated build tags or "none"
    pub const VERSION: &str = "core/version";
}

/// Configuration endpoints
pub mod config {

    /// create the config for a remote.
    ///
    /// This takes the following parameters:
    ///
    /// - name - name of remote
    /// - parameters - a map of \{ "key": "value" \} pairs
    /// - type - type of the new remote
    /// - opt - a dictionary of options to control the configuration
    ///     - obscure - declare passwords are plain and need obscuring
    ///     - noObscure - declare passwords are already obscured and don't need obscuring
    ///     - noOutput - don't print anything to stdout
    ///     - nonInteractive - don't interact with a user, return questions
    ///     - continue - continue the config process with an answer
    ///     - all - ask all the config questions not just the post config ones
    ///     - state - state to restart with - used with continue
    ///     - result - result to restart with - used with continue
    ///
    ///
    /// See the [config create](/commands/rclone_config_create/) command for more information on the above.
    pub const CREATE: &str = "config/create";

    /// Delete a remote in the config file.
    ///
    /// Parameters:
    ///
    /// - name - name of remote to delete
    ///
    /// See the [config delete](/commands/rclone_config_delete/) command for more information on the above.
    pub const DELETE: &str = "config/delete";

    /// Dumps the config file.
    ///
    /// Returns a JSON object:
    /// - key: value
    ///
    /// Where keys are remote names and values are the config parameters.
    ///
    /// See the [config dump](/commands/rclone_config_dump/) command for more information on the above.
    pub const DUMP: &str = "config/dump";

    // /// Get a remote in the config file.
    // ///
    // /// Parameters:
    // ///
    // /// - name - name of remote to get
    // ///
    // /// See the [config dump](/commands/rclone_config_dump/) command for more information on the above.
    // pub const GET: &str = "config/get";

    /// Lists the remotes in the config file and defined in environment variables.
    ///
    /// Returns
    /// - remotes - array of remote names
    ///
    /// See the [listremotes](/commands/rclone_listremotes/) command for more information on the above.
    pub const LISTREMOTES: &str = "config/listremotes";

    /// Get the status of the OAuth authentication server.
    ///
    /// Returns the current status of the OAuth authentication server.
    ///
    /// Returns a JSON object:
    /// - status - "running" or "stopped"
    /// - authUrl - URL for the authorization (only if status is "running")
    ///
    /// Eg
    ///
    /// ```text
    /// {
    /// "status": "running",
    /// "authUrl": "http://127.0.0.1:53682/auth?state=..."
    /// }
    /// ```
    pub const OAUTHSTATUS: &str = "config/oauthstatus";

    /// Stop any running OAuth authentication server.
    ///
    /// Stops the OAuth authentication server if one is running.
    ///
    /// This can be used to recover from an interrupted OAuth flow without
    /// restarting rclone. If no OAuth authentication is in progress, an error
    /// is returned.
    pub const OAUTHSTOP: &str = "config/oauthstop";

    // /// password the config for a remote.
    // ///
    // /// This takes the following parameters:
    // ///
    // /// - name - name of remote
    // /// - parameters - a map of \{ "key": "value" \} pairs
    // ///
    // ///
    // /// See the [config password](/commands/rclone_config_password/) command for more information on the above.
    // pub const PASSWORD: &str = "config/password";

    /// Reads the config file path and other important paths.
    ///
    /// Returns a JSON object with the following keys:
    ///
    /// - config: path to config file
    /// - cache: path to root of cache directory
    /// - temp: path to root of temporary directory
    ///
    /// Eg
    ///
    /// ```text
    /// {
    /// "cache": "/home/USER/.cache/rclone",
    /// "config": "/home/USER/.rclone.conf",
    /// "temp": "/tmp"
    /// }
    ///
    /// ```
    /// See the [config paths](/commands/rclone_config_paths/) command for more information on the above.
    pub const PATHS: &str = "config/paths";

    /// Shows how providers are configured in the config file.
    ///
    /// Returns a JSON object:
    /// - providers - array of objects
    ///
    /// See the [config providers](/commands/rclone_config_providers/) command
    /// for more information on the above.
    ///
    /// Note that the Options blocks are in the same format as returned by
    /// "options/info". They are described in the
    /// [option blocks](#option-blocks) section.
    pub const PROVIDERS: &str = "config/providers";

    /// Set the path of the config file
    ///
    /// Parameters:
    ///
    /// - path - path to the config file to use
    pub const SETPATH: &str = "config/setpath";

    /// Unlock the config file.
    ///
    /// Unlocks the config file if it is locked.
    ///
    /// Parameters:
    ///
    /// - 'configPassword' - password to unlock the config file
    ///
    /// A good idea is to disable AskPassword before making this call
    pub const UNLOCK: &str = "config/unlock";

    // /// Unset keys in a remote in the config file.
    // ///
    // /// Parameters:
    // ///
    // /// - name - name of remote
    // /// - keys - a list of key names to remove
    // ///
    // /// Returns:
    // ///
    // /// - removed - a list of the keys that were actually removed
    // ///
    // /// See the [config unset](/commands/rclone_config_unset/) command for more information on the above.
    // pub const UNSET: &str = "config/unset";

    /// update the config for a remote.
    ///
    /// This takes the following parameters:
    ///
    /// - name - name of remote
    /// - parameters - a map of \{ "key": "value" \} pairs
    /// - opt - a dictionary of options to control the configuration
    ///     - obscure - declare passwords are plain and need obscuring
    ///     - noObscure - declare passwords are already obscured and don't need obscuring
    ///     - noOutput - don't print anything to stdout
    ///     - nonInteractive - don't interact with a user, return questions
    ///     - continue - continue the config process with an answer
    ///     - all - ask all the config questions not just the post config ones
    ///     - state - state to restart with - used with continue
    ///     - result - result to restart with - used with continue
    ///
    ///
    /// See the [config update](/commands/rclone_config_update/) command for more information on the above.
    pub const UPDATE: &str = "config/update";
}

/// Job management endpoints
pub mod job {

    /// Run a batch of rclone rc commands concurrently.
    ///
    /// This takes the following parameters:
    ///
    /// - concurrency - int - do this many commands concurrently. Defaults to `--transfers` if not set.
    /// - inputs - an list of inputs to the commands with an extra `_path` parameter
    ///
    /// ```json
    /// {
    ///     "_path": "rc/path",
    ///     "param1": "parameter for the path as documented",
    ///     "param2": "parameter for the path as documented, etc",
    /// }
    /// ```
    ///
    /// The inputs may use `_async`, `_group`, `_config` and `_filter` as normal when using the rc.
    ///
    /// Returns:
    ///
    /// - results - a list of results from the commands with one entry for each in inputs.
    ///
    /// For example:
    ///
    /// ```sh
    /// rclone rc job/batch --json '{
    ///   "inputs": [
    ///     {
    ///       "_path": "rc/noop",
    ///       "parameter": "OK"
    ///     },
    ///     {
    ///       "_path": "rc/error",
    ///       "parameter": "BAD"
    ///     }
    ///   ]
    /// }
    /// '
    /// ```
    ///
    /// Gives the result:
    ///
    /// ```json
    /// {
    ///   "results": [
    ///     {
    ///       "parameter": "OK"
    ///     },
    ///     {
    ///       "error": "arbitrary error on input map[parameter:BAD]",
    ///       "input": {
    ///         "parameter": "BAD"
    ///       },
    ///       "path": "rc/error",
    ///       "status": 500
    ///     }
    ///   ]
    /// }
    /// ```
    pub const BATCH: &str = "job/batch";

    // /// Lists the IDs of the running jobs
    // ///
    // /// Parameters: None.
    // ///
    // /// Results:
    // ///
    // /// - executeId - string id of rclone executing (change after restart)
    // /// - jobids - array of integer job ids (starting at 1 on each restart)
    // /// - runningIds - array of integer job ids that are running
    // /// - finishedIds - array of integer job ids that are finished
    // pub const LIST: &str = "job/list";

    /// Reads the status of the job ID
    ///
    /// Parameters:
    ///
    /// - jobid - id of the job (integer).
    ///
    /// Results:
    ///
    /// - finished - boolean
    /// - duration - time in seconds that the job ran for
    /// - endTime - time the job finished (e.g. "2018-10-26T18:50:20.528746884+01:00")
    /// - error - error from the job or empty string for no error
    /// - finished - boolean whether the job has finished or not
    /// - id - as passed in above
    /// - executeId - rclone instance ID (changes after restart); combined with id uniquely identifies a job
    /// - startTime - time the job started (e.g. "2018-10-26T18:50:20.528336039+01:00")
    /// - success - boolean - true for success false otherwise
    /// - output - output of the job as would have been returned if called synchronously
    /// - progress - output of the progress related to the underlying job
    pub const STATUS: &str = "job/status";

    /// Stop the running job
    ///
    /// Parameters:
    ///
    /// - jobid - id of the job (integer).
    pub const STOP: &str = "job/stop";

    /// Stop all running jobs in a group
    ///
    /// Parameters:
    ///
    /// - group - name of the group (string).
    pub const STOPGROUP: &str = "job/stopgroup";
}

/// File operation endpoints
pub mod operations {

    /// Perform archive create, extract, or list operations cleanly in process.
    pub const ARCHIVE: &str = "operations/archive";

    /// Perform cryptcheck on encrypted remotes directly in process.
    pub const CRYPTCHECK: &str = "operations/cryptcheck";

    /// Read file content directly in process.
    pub const CAT: &str = "operations/cat";

    /// Return the space used on the remote
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    ///
    /// The result is as returned from rclone about --json
    ///
    /// See the [about](/commands/rclone_about/) command for more information on the above.
    pub const ABOUT: &str = "operations/about";

    /// check the source and destination are the same
    ///
    /// Checks the files in the source and destination match.  It compares
    /// sizes and hashes and logs a report of files that don't
    /// match.  It doesn't alter the source or destination.
    ///
    /// This takes the following parameters:
    ///
    /// - srcFs - a remote name string e.g. "drive:" for the source, "/" for local filesystem
    /// - dstFs - a remote name string e.g. "drive2:" for the destination, "/" for local filesystem
    /// - download - check by downloading rather than with hash
    /// - checkFileHash - treat checkFileFs:checkFileRemote as a SUM file with hashes of given type
    /// - checkFileFs - treat checkFileFs:checkFileRemote as a SUM file with hashes of given type
    /// - checkFileRemote - treat checkFileFs:checkFileRemote as a SUM file with hashes of given type
    /// - oneWay -  check one way only, source files must exist on remote
    /// - combined - make a combined report of changes (default false)
    /// - missingOnSrc - report all files missing from the source (default true)
    /// - missingOnDst - report all files missing from the destination (default true)
    /// - match - report all matching files (default false)
    /// - differ - report all non-matching files (default true)
    /// - error - report all files with errors (hashing or reading) (default true)
    ///
    /// If you supply the download flag, it will download the data from
    /// both remotes and check them against each other on the fly.  This can
    /// be useful for remotes that don't support hashes or if you really want
    /// to check all the data.
    ///
    /// If you supply the size-only global flag, it will only compare the sizes not
    /// the hashes as well.  Use this for a quick check.
    ///
    /// If you supply the checkFileHash option with a valid hash name, the
    /// checkFileFs:checkFileRemote must point to a text file in the SUM
    /// format. This treats the checksum file as the source and dstFs as the
    /// destination. Note that srcFs is not used and should not be supplied in
    /// this case.
    ///
    /// Returns:
    ///
    /// - success - true if no error, false otherwise
    /// - status - textual summary of check, OK or text string
    /// - hashType - hash used in check, may be missing
    /// - combined - array of strings of combined report of changes
    /// - missingOnSrc - array of strings of all files missing from the source
    /// - missingOnDst - array of strings of all files missing from the destination
    /// - match - array of strings of all matching files
    /// - differ - array of strings of all non-matching files
    /// - error - array of strings of all files with errors (hashing or reading)
    pub const CHECK: &str = "operations/check";

    /// Remove trashed files in the remote or path
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    ///
    /// See the [cleanup](/commands/rclone_cleanup/) command for more information on the above.
    pub const CLEANUP: &str = "operations/cleanup";

    /// Copy a file from source remote to destination remote
    ///
    /// This takes the following parameters:
    ///
    /// - srcFs - a remote name string e.g. "drive:" for the source, "/" for local filesystem
    /// - srcRemote - a path within that remote e.g. "file.txt" for the source
    /// - dstFs - a remote name string e.g. "drive2:" for the destination, "/" for local filesystem
    /// - dstRemote - a path within that remote e.g. "file2.txt" for the destination
    pub const COPYFILE: &str = "operations/copyfile";

    /// Copy the URL to the object
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "dir"
    /// - url - string, URL to read from
    ///  - autoFilename - boolean, set to true to retrieve destination file name from url
    ///
    /// See the [copyurl](/commands/rclone_copyurl/) command for more information on the above.
    pub const COPYURL: &str = "operations/copyurl";

    // /// Remove files in the path
    // ///
    // /// This takes the following parameters:
    // ///
    // /// - fs - a remote name string e.g. "drive:"
    // ///
    // /// See the [delete](/commands/rclone_delete/) command for more information on the above.
    // pub const DELETE: &str = "operations/delete";

    /// Remove the single file pointed to
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "dir"
    ///
    /// See the [deletefile](/commands/rclone_deletefile/) command for more information on the above.
    pub const DELETEFILE: &str = "operations/deletefile";

    /// Return information about the remote
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    ///
    /// This returns info about the remote passed in;
    ///
    /// ```text
    /// {
    ///         // optional features and whether they are available or not
    ///         "Features": {
    ///                 "About": true,
    ///                 "BucketBased": false,
    ///                 "BucketBasedRootOK": false,
    ///                 "CanHaveEmptyDirectories": true,
    ///                 "CaseInsensitive": false,
    ///                 "ChangeNotify": false,
    ///                 "CleanUp": false,
    ///                 "Command": true,
    ///                 "Copy": false,
    ///                 "DirCacheFlush": false,
    ///                 "DirMove": true,
    ///                 "Disconnect": false,
    ///                 "DuplicateFiles": false,
    ///                 "GetTier": false,
    ///                 "IsLocal": true,
    ///                 "ListR": false,
    ///                 "MergeDirs": false,
    ///                 "MetadataInfo": true,
    ///                 "Move": true,
    ///                 "OpenWriterAt": true,
    ///                 "PublicLink": false,
    ///                 "Purge": true,
    ///                 "PutStream": true,
    ///                 "PutUnchecked": false,
    ///                 "ReadMetadata": true,
    ///                 "ReadMimeType": false,
    ///                 "ServerSideAcrossConfigs": false,
    ///                 "SetTier": false,
    ///                 "SetWrapper": false,
    ///                 "Shutdown": false,
    ///                 "SlowHash": true,
    ///                 "SlowModTime": false,
    ///                 "UnWrap": false,
    ///                 "UserInfo": false,
    ///                 "UserMetadata": true,
    ///                 "WrapFs": false,
    ///                 "WriteMetadata": true,
    ///                 "WriteMimeType": false
    ///         },
    ///         // Names of hashes available
    ///         "Hashes": [
    ///                 "md5",
    ///                 "sha1",
    ///                 "whirlpool",
    ///                 "crc32",
    ///                 "sha256",
    ///                 "dropbox",
    ///                 "mailru",
    ///                 "quickxor"
    ///         ],
    ///         "Name": "local",        // Name as created
    ///         "Precision": 1,         // Precision of timestamps in ns
    ///         "Root": "/",            // Path as created
    ///         "String": "Local file system at /", // how the remote will appear in logs
    ///         // Information about the system metadata for this backend
    ///         "MetadataInfo": {
    ///                 "System": {
    ///                         "atime": {
    ///                                 "Help": "Time of last access",
    ///                                 "Type": "RFC 3339",
    ///                                 "Example": "2006-01-02T15:04:05.999999999Z07:00"
    ///                         },
    ///                         "btime": {
    ///                                 "Help": "Time of file birth (creation)",
    ///                                 "Type": "RFC 3339",
    ///                                 "Example": "2006-01-02T15:04:05.999999999Z07:00"
    ///                         },
    ///                         "gid": {
    ///                                 "Help": "Group ID of owner",
    ///                                 "Type": "decimal number",
    ///                                 "Example": "500"
    ///                         },
    ///                         "mode": {
    ///                                 "Help": "File type and mode",
    ///                                 "Type": "octal, unix style",
    ///                                 "Example": "0100664"
    ///                         },
    ///                         "mtime": {
    ///                                 "Help": "Time of last modification",
    ///                                 "Type": "RFC 3339",
    ///                                 "Example": "2006-01-02T15:04:05.999999999Z07:00"
    ///                         },
    ///                         "rdev": {
    ///                                 "Help": "Device ID (if special file)",
    ///                                 "Type": "hexadecimal",
    ///                                 "Example": "1abc"
    ///                         },
    ///                         "uid": {
    ///                                 "Help": "User ID of owner",
    ///                                 "Type": "decimal number",
    ///                                 "Example": "500"
    ///                         }
    ///                 },
    ///                 "Help": "Textual help string\n"
    ///         }
    /// }
    /// ```
    ///
    /// This command does not have a command line equivalent so use this instead:
    ///
    /// ```text
    /// rclone rc --loopback operations/fsinfo fs=remote:
    /// ```
    pub const FSINFO: &str = "operations/fsinfo";

    /// Produces a hashsum file for all the objects in the path.
    ///
    /// Produces a hash file for all the objects in the path using the hash
    /// named.  The output is in the same format as the standard
    /// md5sum/sha1sum tool.
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:" for the source, "/" for local filesystem
    ///     - this can point to a file and just that file will be returned in the listing.
    /// - hashType - type of hash to be used
    /// - download - check by downloading rather than with hash (boolean)
    /// - base64 - output the hashes in base64 rather than hex (boolean)
    ///
    /// If you supply the download flag, it will download the data from the
    /// remote and create the hash on the fly. This can be useful for remotes
    /// that don't support the given hash or if you really want to check all
    /// the data.
    ///
    /// Note that if you wish to supply a checkfile to check hashes against
    /// the current files then you should use operations/check instead of
    /// operations/hashsum.
    ///
    /// Returns:
    ///
    /// - hashsum - array of strings of the hashes
    /// - hashType - type of hash used
    ///
    /// Example:
    ///
    /// ```text
    /// $ rclone rc --loopback operations/hashsum fs=bin hashType=MD5 download=true base64=true
    /// {
    /// "hashType": "md5",
    /// "hashsum": [
    /// "WTSVLpuiXyJO_kGzJerRLg==  backend-versions.sh",
    /// "v1b_OlWCJO9LtNq3EIKkNQ==  bisect-go-rclone.sh",
    /// "VHbmHzHh4taXzgag8BAIKQ==  bisect-rclone.sh",
    /// ]
    /// }
    ///
    /// ```
    /// See the [hashsum](/commands/rclone_hashsum/) command for more information on the above.
    pub const HASHSUM: &str = "operations/hashsum";

    /// Produces a hash for a single file.
    ///
    /// Produces a hash for a single file using the hash named.
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "file.txt"
    /// - hashType - type of hash to be used
    /// - download - check by downloading rather than with hash (boolean)
    /// - base64 - output the hashes in base64 rather than hex (boolean)
    ///
    /// If you supply the download flag, it will download the data from the
    /// remote and create the hash on the fly. This can be useful for remotes
    /// that don't support the given hash or if you really want to read all
    /// the data.
    ///
    /// Returns:
    ///
    /// - hash - hash for the file
    /// - hashType - type of hash used
    ///
    /// Example:
    ///
    /// ```text
    /// $ rclone rc --loopback operations/hashsumfile fs=/ remote=/bin/bash hashType=MD5 download=true base64=true
    /// {
    /// "hashType": "md5",
    /// "hash": "MDMw-fG2YXs7Uz5Nz-H68A=="
    /// }
    ///
    /// ```
    /// See the [hashsum](/commands/rclone_hashsum/) command for more information on the above.
    pub const HASHSUMFILE: &str = "operations/hashsumfile";

    /// List the given remote and path in JSON format
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "dir"
    /// - opt - a dictionary of options to control the listing (optional)
    ///     - recurse - If set recurse directories
    ///     - noModTime - If set return modification time
    ///     - showEncrypted -  If set show decrypted names
    ///     - showOrigIDs - If set show the IDs for each item if known
    ///     - showHash - If set return a dictionary of hashes
    ///     - noMimeType - If set don't show mime types
    ///     - dirsOnly - If set only show directories
    ///     - filesOnly - If set only show files
    ///     - metadata - If set return metadata of objects also
    ///     - hashTypes - array of strings of hash types to show if showHash set
    ///
    /// Returns:
    ///
    /// - list
    ///     - This is an array of objects as described in the lsjson command
    ///
    /// See the [lsjson](/commands/rclone_lsjson/) command for more information on the above and examples.
    pub const LIST: &str = "operations/list";

    /// Make a destination directory or container
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "dir"
    ///
    /// See the [mkdir](/commands/rclone_mkdir/) command for more information on the above.
    pub const MKDIR: &str = "operations/mkdir";

    /// Move a file from source remote to destination remote
    ///
    /// This takes the following parameters:
    ///
    /// - srcFs - a remote name string e.g. "drive:" for the source, "/" for local filesystem
    /// - srcRemote - a path within that remote e.g. "file.txt" for the source
    /// - dstFs - a remote name string e.g. "drive2:" for the destination, "/" for local filesystem
    /// - dstRemote - a path within that remote e.g. "file2.txt" for the destination
    pub const MOVEFILE: &str = "operations/movefile";

    /// Create or retrieve a public link to the given file or folder.
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "dir"
    /// - unlink - boolean - if set removes the link rather than adding it (optional)
    /// - expire - string - the expiry time of the link e.g. "1d" (optional)
    ///
    /// Returns:
    ///
    /// - url - URL of the resource
    ///
    /// See the [link](/commands/rclone_link/) command for more information on the above.
    pub const PUBLICLINK: &str = "operations/publiclink";

    /// Remove a directory or container and all of its contents
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "dir"
    ///
    /// See the [purge](/commands/rclone_purge/) command for more information on the above.
    pub const PURGE: &str = "operations/purge";

    // /// Remove an empty directory or container
    // ///
    // /// This takes the following parameters:
    // ///
    // /// - fs - a remote name string e.g. "drive:"
    // /// - remote - a path within that remote e.g. "dir"
    // ///
    // /// See the [rmdir](/commands/rclone_rmdir/) command for more information on the above.
    // pub const RMDIR: &str = "operations/rmdir";

    /// Remove all the empty directories in the path
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "dir"
    /// - leaveRoot - boolean, set to true not to delete the root
    ///
    /// See the [rmdirs](/commands/rclone_rmdirs/) command for more information on the above.
    pub const RMDIRS: &str = "operations/rmdirs";

    // /// Changes storage tier or class on all files in the path
    // ///
    // /// This takes the following parameters:
    // ///
    // /// - fs - a remote name string e.g. "drive:"
    // ///
    // /// See the [settier](/commands/rclone_settier/) command for more information on the above.
    // pub const SETTIER: &str = "operations/settier";

    // /// Changes storage tier or class on the single file pointed to
    // ///
    // /// This takes the following parameters:
    // ///
    // /// - fs - a remote name string e.g. "drive:"
    // /// - remote - a path within that remote e.g. "dir"
    // pub const SETTIERFILE: &str = "operations/settierfile";

    /// Count the number of bytes and files in remote
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:path/to/dir"
    ///
    /// Returns:
    ///
    /// - count - number of files
    /// - bytes - number of bytes in those files
    ///
    /// See the [size](/commands/rclone_size/) command for more information on the above.
    pub const SIZE: &str = "operations/size";

    /// Give information about the supplied file or directory
    ///
    /// This takes the following parameters
    ///
    /// - fs - a remote name string eg "drive:"
    /// - remote - a path within that remote eg "dir"
    /// - opt - a dictionary of options to control the listing (optional)
    ///     - see operations/list for the options
    ///
    /// The result is
    ///
    /// - item - an object as described in the lsjson command. Will be null if not found.
    ///
    /// Note that if you are only interested in files then it is much more
    /// efficient to set the filesOnly flag in the options.
    ///
    /// See the [lsjson](/commands/rclone_lsjson/) command for more information on the above and examples.
    pub const STAT: &str = "operations/stat";

    /// Upload file using multiform/form-data
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote name string e.g. "drive:"
    /// - remote - a path within that remote e.g. "dir"
    /// - each part in body represents a file to be uploaded
    pub const UPLOADFILE: &str = "operations/uploadfile";
}

/// Synchronization endpoints
pub mod sync {

    /// Perform bidirectional synchronization between two paths.
    ///
    /// <!--- Docs generated by help.go - use go generate to rebuild - DO NOT EDIT --->
    ///
    /// This takes the following parameters:
    ///
    /// - path1 (required) - (string) a remote directory string e.g. `drive:path1`
    /// - path2 (required) - (string) a remote directory string e.g. `drive:path2`
    /// - dryRun - (bool) dry-run mode
    /// - backupDir1 - (string) --backup-dir for Path1. Must be a non-overlapping path on
    ///   the same remote.
    /// - backupDir2 - (string) --backup-dir for Path2. Must be a non-overlapping path on
    ///   the same remote.
    /// - checkAccess - (bool) Ensure expected RCLONE_TEST files are found on both
    ///   Path1 and Path2 filesystems, else abort.
    /// - checkFilename - (string) Filename for --check-access (default: RCLONE_TEST)
    /// - checkSync - (string) Controls comparison of final listings: true|false|only
    ///   (default: true)
    /// - compare - (string) Comma-separated list of bisync-specific compare options ex.
    ///   'size,modtime,checksum' (default: 'size,modtime')
    /// - conflictLoser - (ConflictLoserAction) Action to take on the loser of a sync
    ///   conflict (when there is a winner) or on both files (when there is no
    ///   winner): , num, pathname, delete (default: num)
    /// - conflictResolve - (string) Automatically resolve conflicts by preferring the
    ///   version that is: none, path1, path2, newer, older, larger, smaller (default:
    ///   none)
    /// - conflictSuffix - (string) Suffix to use when renaming a --conflict-loser. Can
    ///   be either one string or two comma-separated strings to assign different
    ///   suffixes to Path1/Path2. (default: 'conflict')
    /// - createEmptySrcDirs - (bool) Sync creation and deletion of empty directories.
    ///   (Not compatible with --remove-empty-dirs)
    /// - downloadHash - (bool) Compute hash by downloading when otherwise
    ///   unavailable. (warning: may be slow and use lots of data!)
    /// - filtersFile - (string) Read filtering patterns from a file
    /// - force - (bool) Bypass --max-delete safety check and run the sync. Consider
    ///   using with --verbose
    /// - ignoreListingChecksum - (bool) Do not use checksums for listings (add --ignore-
    ///   checksum to additionally skip post-copy checksum checks)
    /// - maxLock - (Duration) Consider lock files older than this to be expired
    ///   (default: 0 (never expire)) (minimum: 2m)
    /// - noCleanup - (bool) Retain working files (useful for troubleshooting and
    ///   testing).
    /// - noSlowHash - (bool) Ignore listing checksums only on backends where they are
    ///   slow
    /// - recover - (bool) Automatically recover from interruptions without requiring --
    ///   resync.
    /// - removeEmptyDirs - (bool) Remove ALL empty directories at the final cleanup
    ///   step.
    /// - resilient - (bool) Allow future runs to retry after certain less-serious
    ///   errors, instead of requiring --resync.
    /// - resync - (bool) Performs the resync run. Equivalent to --resync-mode path1.
    ///   Consider using --verbose or --dry-run first.
    /// - resyncMode - (string) During resync, prefer the version that is: path1,
    ///   path2, newer, older, larger, smaller (default: path1 if --resync, otherwise
    ///   none for no resync.)
    /// - slowHashSyncOnly - (bool) Ignore slow checksums for listings and deltas, but
    ///   still consider them during sync calls.
    /// - workdir - (string) Use custom working dir - useful for testing. (default:
    ///   /home/ncw/.cache/rclone/bisync)
    ///
    /// See [bisync command help](https://rclone.org/commands/rclone_bisync/)
    /// and [full bisync description](https://rclone.org/bisync/)
    /// for more information.
    pub const BISYNC: &str = "sync/bisync";

    /// copy a directory from source remote to destination remote
    ///
    /// This takes the following parameters:
    ///
    /// - srcFs - a remote name string e.g. "drive:src" for the source
    /// - dstFs - a remote name string e.g. "drive:dst" for the destination
    /// - createEmptySrcDirs - create empty src directories on destination if set
    ///
    ///
    /// See the [copy](/commands/rclone_copy/) command for more information on the above.
    pub const COPY: &str = "sync/copy";

    /// move a directory from source remote to destination remote
    ///
    /// This takes the following parameters:
    ///
    /// - srcFs - a remote name string e.g. "drive:src" for the source
    /// - dstFs - a remote name string e.g. "drive:dst" for the destination
    /// - createEmptySrcDirs - create empty src directories on destination if set
    /// - deleteEmptySrcDirs - delete empty src directories if set
    ///
    ///
    /// See the [move](/commands/rclone_move/) command for more information on the above.
    pub const MOVE: &str = "sync/move";

    /// sync a directory from source remote to destination remote
    ///
    /// This takes the following parameters:
    ///
    /// - srcFs - a remote name string e.g. "drive:src" for the source
    /// - dstFs - a remote name string e.g. "drive:dst" for the destination
    /// - createEmptySrcDirs - create empty src directories on destination if set
    ///
    ///
    /// See the [sync](/commands/rclone_sync/) command for more information on the above.
    pub const SYNC: &str = "sync/sync";
}

/// VFS (Virtual File System) endpoints
pub mod vfs {

    /// Forget files or directories in the directory cache.
    ///
    /// This forgets the paths in the directory cache causing them to be
    /// re-read from the remote when needed.
    ///
    /// If no paths are passed in then it will forget all the paths in the
    /// directory cache.
    ///
    /// ```text
    /// rclone rc vfs/forget
    ///
    /// ```
    /// Otherwise pass files or dirs in as file=path or dir=path.  Any
    /// parameter key starting with file will forget that file and any
    /// starting with dir will forget that dir, e.g.
    ///
    /// ```text
    /// rclone rc vfs/forget file=hello file2=goodbye dir=home/junk
    ///
    /// ```
    /// This command takes an "fs" parameter. If this parameter is not
    /// supplied and if there is only one VFS in use then that VFS will be
    /// used. If there is more than one VFS in use then the "fs" parameter
    /// must be supplied.
    pub const FORGET: &str = "vfs/forget";

    /// List active VFSes.
    ///
    /// This lists the active VFSes.
    ///
    /// It returns a list under the key "vfses" where the values are the VFS
    /// names that could be passed to the other VFS commands in the "fs"
    /// parameter.
    pub const LIST: &str = "vfs/list";

    /// Get the status or update the value of the poll-interval option.
    ///
    /// Without any parameter given this returns the current status of the
    /// poll-interval setting.
    ///
    /// When the interval=duration parameter is set, the poll-interval value
    /// is updated and the polling function is notified.
    /// Setting interval=0 disables poll-interval.
    ///
    /// ```text
    /// rclone rc vfs/poll-interval interval=5m
    ///
    /// ```
    /// The timeout=duration parameter can be used to specify a time to wait
    /// for the current poll function to apply the new value.
    /// If timeout is less or equal 0, which is the default, wait indefinitely.
    ///
    /// The new poll-interval value will only be active when the timeout is
    /// not reached.
    ///
    /// If poll-interval is updated or disabled temporarily, some changes
    /// might not get picked up by the polling function, depending on the
    /// used remote.
    ///
    /// This command takes an "fs" parameter. If this parameter is not
    /// supplied and if there is only one VFS in use then that VFS will be
    /// used. If there is more than one VFS in use then the "fs" parameter
    /// must be supplied.
    pub const POLL_INTERVAL: &str = "vfs/poll-interval";

    /// Queue info for a VFS.
    ///
    /// This returns info about the upload queue for the selected VFS.
    ///
    /// This is only useful if `--vfs-cache-mode` > off. If you call it when
    /// the `--vfs-cache-mode` is off, it will return an empty result.
    ///
    /// ```text
    /// {
    /// "queue": // an array of files queued for upload
    /// [
    /// {
    /// "name":      "file",   // string: name (full path) of the file,
    /// "id":        123,      // integer: id of this item in the queue,
    /// "size":      79,       // integer: size of the file in bytes
    /// "expiry":    1.5       // float: time until file is eligible for transfer, lowest goes first
    /// "tries":     1,        // integer: number of times we have tried to upload
    /// "delay":     5.0,      // float: seconds between upload attempts
    /// "uploading": false,    // boolean: true if item is being uploaded
    /// },
    /// ],
    /// }
    ///
    /// ```
    /// The `expiry` time is the time until the file is eligible for being
    /// uploaded in floating point seconds. This may go negative. As rclone
    /// only transfers `--transfers` files at once, only the lowest
    /// `--transfers` expiry times will have `uploading` as `true`. So there
    /// may be files with negative expiry times for which `uploading` is
    /// `false`.
    ///
    ///
    /// This command takes an "fs" parameter. If this parameter is not
    /// supplied and if there is only one VFS in use then that VFS will be
    /// used. If there is more than one VFS in use then the "fs" parameter
    /// must be supplied.
    pub const QUEUE: &str = "vfs/queue";

    /// Set the expiry time for an item queued for upload.
    ///
    /// Use this to adjust the `expiry` time for an item in the upload queue.
    /// You will need to read the `id` of the item using `vfs/queue` before
    /// using this call.
    ///
    /// You can then set `expiry` to a floating point number of seconds from
    /// now when the item is eligible for upload. If you want the item to be
    /// uploaded as soon as possible then set it to a large negative number (eg
    /// -1000000000). If you want the upload of the item to be delayed
    /// for a long time then set it to a large positive number.
    ///
    /// Setting the `expiry` of an item which has already has started uploading
    /// will have no effect - the item will carry on being uploaded.
    ///
    /// This will return an error if called with `--vfs-cache-mode` off or if
    /// the `id` passed is not found.
    ///
    /// This takes the following parameters
    ///
    /// - `fs` - select the VFS in use (optional)
    /// - `id` - a numeric ID as returned from `vfs/queue`
    /// - `expiry` - a new expiry time as floating point seconds
    /// - `relative` - if set, expiry is to be treated as relative to the current expiry (optional, boolean)
    ///
    /// This returns an empty result on success, or an error.
    ///
    ///
    /// This command takes an "fs" parameter. If this parameter is not
    /// supplied and if there is only one VFS in use then that VFS will be
    /// used. If there is more than one VFS in use then the "fs" parameter
    /// must be supplied.
    pub const QUEUE_SET_EXPIRY: &str = "vfs/queue-set-expiry";

    /// Refresh the directory cache.
    ///
    /// This reads the directories for the specified paths and freshens the
    /// directory cache.
    ///
    /// If no paths are passed in then it will refresh the root directory.
    ///
    /// ```text
    /// rclone rc vfs/refresh
    ///
    /// ```
    /// Otherwise pass directories in as dir=path. Any parameter key
    /// starting with dir will refresh that directory, e.g.
    ///
    /// ```text
    /// rclone rc vfs/refresh dir=home/junk dir2=data/misc
    ///
    /// ```
    /// If the parameter recursive=true is given the whole directory tree
    /// will get refreshed. This refresh will use --fast-list if enabled.
    ///
    /// This command takes an "fs" parameter. If this parameter is not
    /// supplied and if there is only one VFS in use then that VFS will be
    /// used. If there is more than one VFS in use then the "fs" parameter
    /// must be supplied.
    pub const REFRESH: &str = "vfs/refresh";

    /// Stats for a VFS.
    ///
    /// This returns stats for the selected VFS.
    ///
    /// ```text
    /// {
    /// // Status of the disk cache - only present if --vfs-cache-mode > off
    /// "diskCache": {
    /// "bytesUsed": 0,
    /// "erroredFiles": 0,
    /// "files": 0,
    /// "hashType": 1,
    /// "outOfSpace": false,
    /// "path": "/home/user/.cache/rclone/vfs/local/mnt/a",
    /// "pathMeta": "/home/user/.cache/rclone/vfsMeta/local/mnt/a",
    /// "uploadsInProgress": 0,
    /// "uploadsQueued": 0
    /// },
    /// "fs": "/mnt/a",
    /// "inUse": 1,
    /// // Status of the in memory metadata cache
    /// "metadataCache": {
    /// "dirs": 1,
    /// "files": 0
    /// },
    /// // Options as returned by options/get
    /// "opt": {
    /// "CacheMaxAge": 3600000000000,
    /// // ...
    /// "WriteWait": 1000000000
    /// }
    /// }
    ///
    ///
    /// ```
    /// This command takes an "fs" parameter. If this parameter is not
    /// supplied and if there is only one VFS in use then that VFS will be
    /// used. If there is more than one VFS in use then the "fs" parameter
    /// must be supplied.
    pub const STATS: &str = "vfs/stats";
}

/// Mount endpoints
pub mod mount {

    /// Show current mount points
    ///
    /// This shows currently mounted points, which can be used for performing an unmount.
    ///
    /// This takes no parameters and returns
    ///
    /// - mountPoints: list of current mount points
    ///
    /// Eg
    ///
    /// ```text
    /// rclone rc mount/listmounts
    /// ```
    pub const LISTMOUNTS: &str = "mount/listmounts";

    /// Create a new mount point
    ///
    /// rclone allows Linux, FreeBSD, macOS and Windows to mount any of
    /// Rclone's cloud storage systems as a file system with FUSE.
    ///
    /// If no mountType is provided, the priority is given as follows: 1. mount 2.cmount 3.mount2
    ///
    /// This takes the following parameters:
    ///
    /// - fs - a remote path to be mounted (required)
    /// - mountPoint: valid path on the local machine (required)
    /// - mountType: one of the values (mount, cmount, mount2) specifies the mount implementation to use
    /// - mountOpt: a JSON object with Mount options in.
    /// - vfsOpt: a JSON object with VFS options in.
    ///
    /// Alternatively, you can pass VFS and Mount options flat at the top level of the parameter map. The option names are the same as their CLI flags without '--' and with '-' replaced by '_' (e.g. 'vfs_cache_mode' instead of 'CacheMode' inside 'vfsOpt', and 'volname' instead of 'VolName' inside 'mountOpt').
    ///
    /// If both flat parameters and nested 'vfsOpt'/'mountOpt' blocks are supplied, the parameters in the nested blocks will take precedence.
    ///
    /// On Windows mountPoint may be set to "*" to assign the next available
    /// drive letter automatically, or a network share UNC path (e.g.
    /// "\\server\share") to mount as a network drive. In these cases the
    /// actual drive letter is chosen at mount time.
    ///
    /// This returns the following values:
    ///
    /// - mountPoint: the actual mount point that was used (this may differ
    ///   from the input, e.g. on Windows when "*" is passed the allocated
    ///   drive letter is returned)
    ///
    /// Example:
    ///
    /// ```console
    /// rclone rc mount/mount fs=mydrive: mountPoint=/home/<user>/mountPoint
    /// rclone rc mount/mount fs=mydrive: mountPoint=/home/<user>/mountPoint mountType=mount
    /// rclone rc mount/mount fs=TestDrive: mountPoint=/mnt/tmp vfsOpt='{"CacheMode": 2}' mountOpt='{"AllowOther": true}'
    /// rclone rc mount/mount fs=TestDrive: mountPoint=/mnt/tmp vfs_cache_mode=writes volname=MyTestVolume
    /// rclone rc mount/mount fs=mydrive: mountPoint=* mountType=cmount
    /// ```
    ///
    /// The vfsOpt are as described in options/get and can be seen in the
    /// "vfs" section when running and the mountOpt can be seen in the "mount" section:
    ///
    /// ```console
    /// rclone rc options/get
    /// ```
    pub const MOUNT: &str = "mount/mount";

    /// Show all possible mount types
    ///
    /// This shows all possible mount types and returns them as a list.
    ///
    /// This takes no parameters and returns
    ///
    /// - mountTypes: list of mount types
    ///
    /// The mount types are strings like "mount", "mount2", "cmount" and can
    /// be passed to mount/mount as the mountType parameter.
    ///
    /// Eg
    ///
    /// ```text
    /// rclone rc mount/types
    /// ```
    pub const TYPES: &str = "mount/types";

    /// Unmount selected active mount
    ///
    /// rclone allows Linux, FreeBSD, macOS and Windows to
    /// mount any of Rclone's cloud storage systems as a file system with
    /// FUSE.
    ///
    /// This takes the following parameters:
    ///
    /// - mountPoint: valid path on the local machine where the mount was created (required)
    ///
    /// Example:
    ///
    /// ```text
    /// rclone rc mount/unmount mountPoint=/home/<user>/mountPoint
    /// ```
    pub const UNMOUNT: &str = "mount/unmount";

    /// Unmount all active mounts
    ///
    /// rclone allows Linux, FreeBSD, macOS and Windows to
    /// mount any of Rclone's cloud storage systems as a file system with
    /// FUSE.
    ///
    /// This takes no parameters and returns error if unmount does not succeed.
    ///
    /// Eg
    ///
    /// ```text
    /// rclone rc mount/unmountall
    /// ```
    pub const UNMOUNTALL: &str = "mount/unmountall";
}

/// File system cache endpoints
pub mod fscache {

    /// Clear the Fs cache.
    ///
    /// This clears the fs cache. This is where remotes created from backends
    /// are cached for a short while to make repeated rc calls more efficient.
    ///
    /// If you change the parameters of a backend then you may want to call
    /// this to clear an existing remote out of the cache before re-creating
    /// it.
    pub const CLEAR: &str = "fscache/clear";

    /// Returns the number of entries in the fs cache.
    ///
    /// This returns the number of entries in the fs cache.
    ///
    /// Returns
    /// - entries - number of items in the cache
    pub const ENTRIES: &str = "fscache/entries";
}

/// Option management endpoints
pub mod options {

    /// List all the option blocks
    ///
    /// Returns:
    /// - options - a list of the options block names
    pub const BLOCKS: &str = "options/blocks";

    /// Get all the global options
    ///
    /// Returns an object where keys are option block names and values are an
    /// object with the current option values in.
    ///
    /// Parameters:
    ///
    /// - blocks: optional string of comma separated blocks to include
    ///     - all are included if this is missing or ""
    ///
    /// Note that these are the global options which are unaffected by use of
    /// the _config and _filter parameters. If you wish to read the parameters
    /// set in _config or _filter use options/local.
    ///
    /// This shows the internal names of the option within rclone which should
    /// map to the external options very easily with a few exceptions.
    pub const GET: &str = "options/get";

    /// Get info about all the global options
    ///
    /// Returns an object where keys are option block names and values are an
    /// array of objects with info about each options.
    ///
    /// Parameters:
    ///
    /// - blocks: optional string of comma separated blocks to include
    ///     - all are included if this is missing or ""
    ///
    /// These objects are in the same format as returned by "config/providers". They are
    /// described in the [option blocks](#option-blocks) section.
    pub const INFO: &str = "options/info";

    // /// Get the currently active config for this call
    // ///
    // /// Returns an object with the keys "config" and "filter".
    // /// The "config" key contains the local config and the "filter" key contains
    // /// the local filters.
    // ///
    // /// Note that these are the local options specific to this rc call. If
    // /// _config was not supplied then they will be the global options.
    // /// Likewise with "_filter".
    // ///
    // /// This call is mostly useful for seeing if _config and _filter passing
    // /// is working.
    // ///
    // /// This shows the internal names of the option within rclone which should
    // /// map to the external options very easily with a few exceptions.
    // pub const LOCAL: &str = "options/local";

    /// Set an option
    ///
    /// Parameters:
    ///
    /// - option block name containing an object with
    ///   - key: value
    ///
    /// Repeated as often as required.
    ///
    /// Only supply the options you wish to change.  If an option is unknown
    /// it will be silently ignored.  Not all options will have an effect when
    /// changed like this.
    ///
    /// For example:
    ///
    /// This sets DEBUG level logs (-vv) (these can be set by number or string)
    ///
    /// ```text
    /// rclone rc options/set --json '{"main": {"LogLevel": "DEBUG"}}'
    /// rclone rc options/set --json '{"main": {"LogLevel": 8}}'
    ///
    /// ```
    /// And this sets INFO level logs (-v)
    ///
    /// ```text
    /// rclone rc options/set --json '{"main": {"LogLevel": "INFO"}}'
    ///
    /// ```
    /// And this sets NOTICE level logs (normal without -v)
    ///
    /// ```text
    /// rclone rc options/set --json '{"main": {"LogLevel": "NOTICE"}}'
    /// ```
    pub const SET: &str = "options/set";
}

/// Serve endpoints
pub mod serve {

    /// Show running servers
    ///
    /// Show running servers with IDs.
    ///
    /// This takes no parameters and returns
    ///
    /// - list: list of running serve commands
    ///
    /// Each list element will have
    ///
    /// - id: ID of the server
    /// - addr: address the server is running on
    /// - params: parameters used to start the server
    ///
    /// Eg
    ///
    /// ```text
    /// rclone rc serve/list
    ///
    /// ```
    /// Returns
    ///
    /// ```json
    /// {
    ///     "list": [
    ///         {
    ///             "addr": "[::]:4321",
    ///             "id": "nfs-ffc2a4e5",
    ///             "params": {
    ///                 "fs": "remote:",
    ///                 "opt": {
    ///                     "ListenAddr": ":4321"
    ///                 },
    ///                 "type": "nfs",
    ///                 "vfsOpt": {
    ///                     "CacheMode": "full"
    ///                 }
    ///             }
    ///         }
    ///     ]
    /// }
    /// ```
    pub const LIST: &str = "serve/list";

    /// Create a new server
    ///
    /// Create a new server with the specified parameters.
    ///
    /// This takes the following parameters:
    ///
    /// - `type` - type of server: `http`, `webdav`, `ftp`, `sftp`, `nfs`, etc.
    /// - `fs` - remote storage path to serve
    /// - `addr` - the ip:port to run the server on, eg ":1234" or "localhost:1234"
    ///
    /// Other parameters are as described in the documentation for the
    /// relevant [rclone serve](/commands/rclone_serve/) command line options.
    /// To translate a command line option to an rc parameter, remove the
    /// leading `--` and replace `-` with `_`, so `--vfs-cache-mode` becomes
    /// `vfs_cache_mode`.
    ///
    /// Option parameters (such as VFS, proxy, and protocol-specific options) can be passed flat at the top level of the parameter map or inside nested JSON objects under the `vfsOpt`, `proxyOpt`, and `opt` keys (e.g. `vfsOpt='{"CacheMode": 2}'`, `proxyOpt='{"AuthProxy": "http://127.0.0.1:8080"}'`). If both flat parameters and nested blocks are supplied, the parameters in the nested blocks will take precedence. Note that global parameters must be set with `_config` and `_filter` as described above.
    ///
    /// Examples:
    ///
    /// ```text
    /// rclone rc serve/start type=nfs fs=remote: addr=:4321 vfs_cache_mode=full
    /// rclone rc serve/start --json '{"type":"nfs","fs":"remote:","addr":":1234","vfs_cache_mode":"full"}'
    /// rclone rc serve/start type=webdav fs=remote: vfsOpt='{"CacheMode": 2}' proxyOpt='{"AuthProxy": "http://127.0.0.1:8080"}'
    ///
    /// ```
    /// This will give the reply
    ///
    /// ```json
    /// {
    ///     "addr": "[::]:4321", // Address the server was started on
    ///     "id": "nfs-ecfc6852" // Unique identifier for the server instance
    /// }
    /// ```
    ///
    /// Or an error if it failed to start.
    ///
    /// Stop the server with `serve/stop` and list the running servers with `serve/list`.
    pub const START: &str = "serve/start";

    /// Unserve selected active serve
    ///
    /// Stops a running `serve` instance by ID.
    ///
    /// This takes the following parameters:
    ///
    /// - id: as returned by serve/start
    ///
    /// This will give an empty response if successful or an error if not.
    ///
    /// Example:
    ///
    /// ```text
    /// rclone rc serve/stop id=12345
    /// ```
    pub const STOP: &str = "serve/stop";

    /// Stop all active servers
    ///
    /// Stop all active servers.
    ///
    /// This will stop all active servers.
    ///
    /// ```text
    /// rclone rc serve/stopall
    /// ```
    pub const STOPALL: &str = "serve/stopall";

    /// Show all possible serve types
    ///
    /// This shows all possible serve types and returns them as a list.
    ///
    /// This takes no parameters and returns
    ///
    /// - types: list of serve types, eg "nfs", "sftp", etc
    ///
    /// The serve types are strings like "serve", "serve2", "cserve" and can
    /// be passed to serve/start as the serveType parameter.
    ///
    /// Eg
    ///
    /// ```text
    /// rclone rc serve/types
    ///
    /// ```
    /// Returns
    ///
    /// ```json
    /// {
    ///     "types": [
    ///         "http",
    ///         "sftp",
    ///         "nfs"
    ///     ]
    /// }
    /// ```
    pub const TYPES: &str = "serve/types";
}

// /// Backend command endpoints
// pub mod backend {

//     /// Runs a backend command.
//     ///
//     /// This takes the following parameters:
//     ///
//     /// - command - a string with the command name
//     /// - fs - a remote name string e.g. "drive:"
//     /// - arg - a list of arguments for the backend command
//     /// - opt - a map of string to string of options
//     ///
//     /// Returns:
//     ///
//     /// - result - result from the backend command
//     ///
//     /// Example:
//     ///
//     ///     rclone rc backend/command command=noop fs=. -o echo=yes -o blue -a path1 -a path2
//     ///
//     /// Returns
//     ///
//     /// ```
//     /// {
//     /// 	"result": {
//     /// 		"arg": [
//     /// 			"path1",
//     /// 			"path2"
//     /// 		],
//     /// 		"name": "noop",
//     /// 		"opt": {
//     /// 			"blue": "",
//     /// 			"echo": "yes"
//     /// 		}
//     /// 	}
//     /// }
//     /// ```
//     ///
//     /// Note that this is the direct equivalent of using this "backend"
//     /// command:
//     ///
//     ///     rclone backend noop . -o echo=yes -o blue path1 path2
//     ///
//     /// Note that arguments must be preceded by the "-a" flag
//     ///
//     /// See the [backend](/commands/rclone_backend/) command for more information.
//     pub const COMMAND: &str = "backend/command";
// }

// /// Debug endpoints
// pub mod debug {

//     /// Set runtime.SetBlockProfileRate for blocking profiling.
//     ///
//     /// SetBlockProfileRate controls the fraction of goroutine blocking events
//     /// that are reported in the blocking profile. The profiler aims to sample
//     /// an average of one blocking event per rate nanoseconds spent blocked.
//     ///
//     /// To include every blocking event in the profile, pass rate = 1. To turn
//     /// off profiling entirely, pass rate <= 0.
//     ///
//     /// After calling this you can use this to see the blocking profile:
//     ///
//     ///     go tool pprof http://localhost:5572/debug/pprof/block
//     ///
//     /// Parameters:
//     ///
//     /// - rate - int
//     pub const SET_BLOCK_PROFILE_RATE: &str = "debug/set-block-profile-rate";

//     /// Call runtime/debug.SetGCPercent for setting the garbage collection target percentage.
//     ///
//     /// SetGCPercent sets the garbage collection target percentage: a collection is triggered
//     /// when the ratio of freshly allocated data to live data remaining after the previous collection
//     /// reaches this percentage. SetGCPercent returns the previous setting. The initial setting is the
//     /// value of the GOGC environment variable at startup, or 100 if the variable is not set.
//     ///
//     /// This setting may be effectively reduced in order to maintain a memory limit.
//     /// A negative percentage effectively disables garbage collection, unless the memory limit is reached.
//     ///
//     /// See https://pkg.go.dev/runtime/debug#SetMemoryLimit for more details.
//     ///
//     /// Parameters:
//     ///
//     /// - gc-percent - int
//     pub const SET_GC_PERCENT: &str = "debug/set-gc-percent";

//     /// Set runtime.SetMutexProfileFraction for mutex profiling.
//     ///
//     /// SetMutexProfileFraction controls the fraction of mutex contention
//     /// events that are reported in the mutex profile. On average 1/rate
//     /// events are reported. The previous rate is returned.
//     ///
//     /// To turn off profiling entirely, pass rate 0. To just read the current
//     /// rate, pass rate < 0. (For n>1 the details of sampling may change.)
//     ///
//     /// Once this is set you can look use this to profile the mutex contention:
//     ///
//     ///     go tool pprof http://localhost:5572/debug/pprof/mutex
//     ///
//     /// Parameters:
//     ///
//     /// - rate - int
//     ///
//     /// Results:
//     ///
//     /// - previousRate - int
//     pub const SET_MUTEX_PROFILE_FRACTION: &str = "debug/set-mutex-profile-fraction";

//     /// Call runtime/debug.SetMemoryLimit for setting a soft memory limit for the runtime.
//     ///
//     /// SetMemoryLimit provides the runtime with a soft memory limit.
//     ///
//     /// The runtime undertakes several processes to try to respect this memory limit, including
//     /// adjustments to the frequency of garbage collections and returning memory to the underlying
//     /// system more aggressively. This limit will be respected even if GOGC=off (or, if SetGCPercent(-1) is executed).
//     ///
//     /// The input limit is provided as bytes, and includes all memory mapped, managed, and not
//     /// released by the Go runtime. Notably, it does not account for space used by the Go binary
//     /// and memory external to Go, such as memory managed by the underlying system on behalf of
//     /// the process, or memory managed by non-Go code inside the same process.
//     /// Examples of excluded memory sources include: OS kernel memory held on behalf of the process,
//     /// memory allocated by C code, and memory mapped by syscall.Mmap (because it is not managed by the Go runtime).
//     ///
//     /// A zero limit or a limit that's lower than the amount of memory used by the Go runtime may cause
//     /// the garbage collector to run nearly continuously. However, the application may still make progress.
//     ///
//     /// The memory limit is always respected by the Go runtime, so to effectively disable this behavior,
//     /// set the limit very high. math.MaxInt64 is the canonical value for disabling the limit, but values
//     /// much greater than the available memory on the underlying system work just as well.
//     ///
//     /// See https://go.dev/doc/gc-guide for a detailed guide explaining the soft memory limit in more detail,
//     /// as well as a variety of common use-cases and scenarios.
//     ///
//     /// SetMemoryLimit returns the previously set memory limit. A negative input does not adjust the limit,
//     /// and allows for retrieval of the currently set memory limit.
//     ///
//     /// Parameters:
//     ///
//     /// - mem-limit - int
//     pub const SET_SOFT_MEMORY_LIMIT: &str = "debug/set-soft-memory-limit";
// }

// /// Plugin control endpoints
// pub mod pluginsctl {

//     /// Add a plugin using url
//     ///
//     /// Used for adding a plugin to the webgui.
//     ///
//     /// This takes the following parameters:
//     ///
//     /// - url - http url of the github repo where the plugin is hosted (http://github.com/rclone/rclone-webui-react).
//     ///
//     /// Example:
//     ///
//     ///    rclone rc pluginsctl/addPlugin
//     pub const ADDPLUGIN: &str = "pluginsctl/addPlugin";

//     /// Get plugins with type criteria
//     ///
//     /// This shows all possible plugins by a mime type.
//     ///
//     /// This takes the following parameters:
//     ///
//     /// - type - supported mime type by a loaded plugin e.g. (video/mp4, audio/mp3).
//     /// - pluginType - filter plugins based on their type e.g. (DASHBOARD, FILE_HANDLER, TERMINAL).
//     ///
//     /// Returns:
//     ///
//     /// - loadedPlugins - list of current production plugins.
//     /// - testPlugins - list of temporarily loaded development plugins, usually running on a different server.
//     ///
//     /// Example:
//     ///
//     ///    rclone rc pluginsctl/getPluginsForType type=video/mp4
//     pub const GETPLUGINSFORTYPE: &str = "pluginsctl/getPluginsForType";

//     /// Get the list of currently loaded plugins
//     ///
//     /// This allows you to get the currently enabled plugins and their details.
//     ///
//     /// This takes no parameters and returns:
//     ///
//     /// - loadedPlugins - list of current production plugins.
//     /// - testPlugins - list of temporarily loaded development plugins, usually running on a different server.
//     ///
//     /// E.g.
//     ///
//     ///    rclone rc pluginsctl/listPlugins
//     pub const LISTPLUGINS: &str = "pluginsctl/listPlugins";

//     /// Show currently loaded test plugins
//     ///
//     /// Allows listing of test plugins with the rclone.test set to true in package.json of the plugin.
//     ///
//     /// This takes no parameters and returns:
//     ///
//     /// - loadedTestPlugins - list of currently available test plugins.
//     ///
//     /// E.g.
//     ///
//     ///     rclone rc pluginsctl/listTestPlugins
//     pub const LISTTESTPLUGINS: &str = "pluginsctl/listTestPlugins";

//     /// Remove a loaded plugin
//     ///
//     /// This allows you to remove a plugin using it's name.
//     ///
//     /// This takes parameters:
//     ///
//     /// - name - name of the plugin in the format `author`/`plugin_name`.
//     ///
//     /// E.g.
//     ///
//     ///    rclone rc pluginsctl/removePlugin name=rclone/video-plugin
//     pub const REMOVEPLUGIN: &str = "pluginsctl/removePlugin";

//     /// Remove  a test plugin
//     ///
//     /// This allows you to remove a plugin using it's name.
//     ///
//     /// This takes the following parameters:
//     ///
//     /// - name - name of the plugin in the format `author`/`plugin_name`.
//     ///
//     /// Example:
//     ///
//     ///     rclone rc pluginsctl/removeTestPlugin name=rclone/rclone-webui-react
//     pub const REMOVETESTPLUGIN: &str = "pluginsctl/removeTestPlugin";
// }

// /// Remote control endpoints
// pub mod rc {

//     /// This returns an error
//     ///
//     /// This returns an error with the input as part of its error string.
//     /// Useful for testing error handling.
//     pub const ERROR: &str = "rc/error";

//     /// This returns an fatal error
//     ///
//     /// This returns an error with the input as part of its error string.
//     /// Useful for testing error handling.
//     pub const FATAL: &str = "rc/fatal";

//     /// List all the registered remote control commands
//     ///
//     /// This lists all the registered remote control commands as a JSON map in
//     /// the commands response.
//     pub const LIST: &str = "rc/list";

//     /// Echo the input to the output parameters
//     ///
//     /// This echoes the input parameters to the output parameters for testing
//     /// purposes.  It can be used to check that rclone is still alive and to
//     /// check that parameter passing is working properly.
//     pub const NOOP: &str = "rc/noop";

//     /// Echo the input to the output parameters requiring auth
//     ///
//     /// This echoes the input parameters to the output parameters for testing
//     /// purposes.  It can be used to check that rclone is still alive and to
//     /// check that parameter passing is working properly.
//     pub const NOOPAUTH: &str = "rc/noopauth";

//     /// This returns an error by panicking
//     ///
//     /// This returns an error with the input as part of its error string.
//     /// Useful for testing error handling.
//     pub const PANIC: &str = "rc/panic";
// }
